# -*- coding: utf-8 -*-
"""AerospaceMaterial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjyReRMMtF1Y_FIKYGBpglNF_GcATMUA
"""

from google.colab import drive
import os

drive.mount('/content/drive')

import zipfile

zip_path = '/content/drive/MyDrive/aircraft_skin_defects.v23i.multiclass.zip'
extract_path = '/content/aircraft_skin_defects'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# ==============================
# 🛰️ Aerospace Material Defect Detection
# ==============================

# --- STEP 1: IMPORTS ---
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils import resample
from collections import Counter
import seaborn as sns

# --- STEP 2: LOAD YOUR DATA ---
# (Assuming you already have numpy arrays: X_train, y_train, X_valid, y_valid, X_test, y_test)
# Example:
# np.load('X_train.npy'), etc.
train_dir = '/content/aircraft_skin_defects/train'
valid_dir = '/content/aircraft_skin_defects/valid'
test_dir  = '/content/aircraft_skin_defects/test'

X_train, y_train = load_images_and_labels(train_dir)
X_valid, y_valid = load_images_and_labels(valid_dir)
X_test, y_test   = load_images_and_labels(test_dir)

X_train_bal, y_train_bal = balance_dataset(X_train, y_train)

print("✅ Data loaded successfully.")
print("Train:", X_train.shape, "Valid:", X_valid.shape, "Test:", X_test.shape)
print("Classes:", np.unique(y_train))

# --- STEP 3: BALANCE DATASET FUNCTION ---
def balance_dataset(X, y):
    X = np.array(X)
    y = np.array(y)

    X_class0 = X[y == 0]
    X_class1 = X[y == 1]

    n_samples = max(len(X_class0), len(X_class1))
    X_class0_bal = resample(X_class0, replace=True, n_samples=n_samples, random_state=42)
    X_class1_bal = resample(X_class1, replace=True, n_samples=n_samples, random_state=42)

    X_bal = np.vstack((X_class0_bal, X_class1_bal))
    y_bal = np.array([0] * n_samples + [1] * n_samples)

    shuffle_idx = np.random.permutation(len(X_bal))
    return X_bal[shuffle_idx], y_bal[shuffle_idx]

# --- STEP 4: BALANCE TRAIN/VALID/TEST ---
X_train_bal, y_train_bal = balance_dataset(X_train, y_train)
X_valid_bal, y_valid_bal = balance_dataset(X_valid, y_valid)
X_test_bal, y_test_bal   = balance_dataset(X_test, y_test)

print("Train labels:", Counter(y_train_bal))
print("Valid labels:", Counter(y_valid_bal))
print("Test labels:", Counter(y_test_bal))

# --- STEP 5: DEFINE MODEL ---
base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # Freeze base model

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
x = Dense(128, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

# --- STEP 6: TRAIN INITIAL MODEL ---
history = model.fit(
    X_train_bal, y_train_bal,
    validation_data=(X_valid_bal, y_valid_bal),
    epochs=10,
    batch_size=32
)

# --- STEP 7: FINE-TUNE ---
for layer in base_model.layers[-30:]:
    layer.trainable = True

model.compile(optimizer=Adam(1e-5), loss='binary_crossentropy', metrics=['accuracy'])

fine_tune_history = model.fit(
    X_train_bal, y_train_bal,
    validation_data=(X_valid_bal, y_valid_bal),
    epochs=10,
    batch_size=32
)

# --- STEP 8: EVALUATE ---
y_pred = (model.predict(X_test_bal) > 0.5).astype(int)
cm = confusion_matrix(y_test_bal, y_pred)
acc = np.trace(cm) / np.sum(cm)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title(f"Confusion Matrix (Accuracy={acc:.2f})")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

print("\nClassification Report:\n")
print(classification_report(y_test_bal, y_pred, target_names=['No Defect', 'Defect']))

# --- STEP 9: TRAINING CURVES ---
plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'] + fine_tune_history.history['accuracy'])
plt.plot(history.history['val_accuracy'] + fine_tune_history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])

plt.subplot(1,2,2)
plt.plot(history.history['loss'] + fine_tune_history.history['loss'])
plt.plot(history.history['val_loss'] + fine_tune_history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'])
plt.show()

# --- STEP 10: SAVE MODEL ---
model.save("Aerospace_Defect_Model.h5")
print("✅ Model saved as Aerospace_Defect_Model.h5")

# ====================================
# 📦 1. Imports
# ====================================
import os
import numpy as np
import pandas as pd
import cv2
from collections import Counter
from sklearn.utils import resample
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.preprocessing.image import ImageDataGenerator


# ====================================
# 🖼️ 2. Load images & labels
# ====================================
def load_images_and_labels(data_dir):
    class_csv = os.path.join(data_dir, '_classes.csv')
    df = pd.read_csv(class_csv)
    df.columns = df.columns.str.strip()

    images, labels = [], []
    for _, row in df.iterrows():
        img_path = os.path.join(data_dir, row['filename'])
        if os.path.exists(img_path):
            img = cv2.imread(img_path)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (224, 224))
            img = img / 255.0
            images.append(img)
            labels.append(row['defect'])

    return np.array(images), np.array(labels)


# ====================================
# ⚖️ 3. Balance dataset with augmentation
# ====================================
def balance_dataset(X, y):
    print("Before balancing:", Counter(y))

    datagen = ImageDataGenerator(
        rotation_range=15,
        width_shift_range=0.1,
        height_shift_range=0.1,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest'
    )

    unique, counts = np.unique(y, return_counts=True)
    majority_class = unique[np.argmax(counts)]
    minority_class = unique[np.argmin(counts)]
    augment_needed = counts.max() - counts.min()

    X_minority = X[y == minority_class]
    y_minority = y[y == minority_class]

    augmented_images, augmented_labels = [], []
    gen = datagen.flow(X_minority, batch_size=1, shuffle=True)
    for i in range(augment_needed):
        aug_img = next(gen)[0]
        augmented_images.append(aug_img)
        augmented_labels.append(minority_class)

    X_bal = np.concatenate([X, np.array(augmented_images)], axis=0)
    y_bal = np.concatenate([y, np.array(augmented_labels)], axis=0)

    print("After balancing:", Counter(y_bal))
    return X_bal, y_bal


# ====================================
# 📂 4. Load datasets
# ====================================
train_dir = '/content/aircraft_skin_defects/train'
valid_dir = '/content/aircraft_skin_defects/valid'
test_dir  = '/content/aircraft_skin_defects/test'

X_train, y_train = load_images_and_labels(train_dir)
X_valid, y_valid = load_images_and_labels(valid_dir)
X_test, y_test   = load_images_and_labels(test_dir)

X_train_bal, y_train_bal = balance_dataset(X_train, y_train)

print("\n✅ Data loaded successfully.")
print("Train:", X_train_bal.shape, "Valid:", X_valid.shape, "Test:", X_test.shape)
print("Classes:", np.unique(y_train_bal))


# ====================================
# 🧠 5. Build MobileNetV2 Model
# ====================================
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # Freeze base layers

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
x = Dense(128, activation='relu')(x)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=output)
model.compile(optimizer=Adam(learning_rate=1e-4), loss='binary_crossentropy', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
# --- Compute class weights ---
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Convert y_train to normal integers if needed
y_train_int = np.array(y_train).astype(int)

# Compute balanced class weights
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_int),
    y=y_train_int
)
class_weights = dict(zip(np.unique(y_train_int), class_weights))
print("Class Weights:", class_weights)

# ====================================
# 🚀 6. Train (Phase 1)
# ====================================
history = model.fit(
    X_train_bal, y_train_bal,
    validation_data=(X_valid, y_valid),
    epochs=10,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stop],
    verbose=1
)

# ====================================
# 🔎 7. Evaluate before fine-tuning
# ====================================
y_pred = (model.predict(X_test) > 0.5).astype("int32")

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No Defect', 'Defect'], yticklabels=['No Defect', 'Defect'])
plt.title(f'Confusion Matrix (Accuracy={model.evaluate(X_test, y_test, verbose=0)[1]:.2f})')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=['No Defect', 'Defect']))


# ====================================
# 🔧 8. Fine-tune (Unfreeze part of base model)
# ====================================
for layer in base_model.layers[-40:]:
    layer.trainable = True

model.compile(optimizer=Adam(learning_rate=1e-5), loss='binary_crossentropy', metrics=['accuracy'])

history_fine = model.fit(
    X_train_bal, y_train_bal,
    validation_data=(X_valid, y_valid),
    epochs=10,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# ====================================
# 🧾 9. Evaluate after fine-tuning
# ====================================
y_pred_fine = (model.predict(X_test) > 0.5).astype("int32")

cm = confusion_matrix(y_test, y_pred_fine)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No Defect', 'Defect'], yticklabels=['No Defect', 'Defect'])
plt.title(f'Confusion Matrix (Fine-tuned Accuracy={model.evaluate(X_test, y_test, verbose=0)[1]:.2f})')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

print("\nClassification Report After Fine-tuning:\n", classification_report(y_test, y_pred_fine, target_names=['No Defect', 'Defect']))


# ====================================
# 💾 10. Save model
# ====================================
model.save("Aerospace_Defect_Finetuned.keras")
print("\n✅ Fine-tuned model saved successfully!")

import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import numpy as np



# Load and preprocess
img_path ="/content/def1.png"
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

# Predict using your trained model
prediction = model.predict(img_array)
label = "Defect" if prediction[0][0] > 0.7 else "No Defect"

# Display
plt.imshow(image.load_img(img_path))
plt.axis('off')
plt.title(f"Predicted: {label} ({prediction[0][0]:.2f})")
plt.show()
